import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export interface AppNotification {
  id: string;
  // Stable key generated by whoever calls addNotification (e.g.
  // "species:hrib-dubovy:2026-08" or "location:123:2026-08-05") — lets the
  // generator run on every app open without ever producing duplicates.
  dedupeKey: string;
  kind: "species" | "location" | "generic";
  title: string;
  body: string;
  createdAt: string;
  read: boolean;
}

const NOTIF_KEY = "rostou:notifications";
const WATCHED_SPECIES_KEY = "rostou:watchedSpecies";
const MAX_NOTIFICATIONS = 40;

interface NotificationContextValue {
  notifications: AppNotification[];
  unreadCount: number;
  loaded: boolean;
  markAllRead: () => void;
  markRead: (id: string) => void;
  addNotification: (n: { dedupeKey: string; kind: AppNotification["kind"]; title: string; body: string }) => void;
  watchedSpecies: string[];
  toggleWatchedSpecies: (id: string) => void;
  // The sheet's open/closed state lives here (not in a screen-local
  // useState) so it can be rendered once, at the app shell's top level —
  // nesting it inside TopBar caused BottomSheet's full-screen absolute
  // positioning to be constrained to TopBar's own thin header height
  // instead of the whole screen.
  sheetOpen: boolean;
  openSheet: () => void;
  closeSheet: () => void;
}

const NotificationContext = createContext<NotificationContextValue | null>(null);

export function NotificationProvider({ children }: { children: ReactNode }) {
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [watchedSpecies, setWatchedSpecies] = useState<string[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [sheetOpen, setSheetOpen] = useState(false);
  // Guards against the persistence effects firing with the empty initial
  // state before AsyncStorage has finished loading, which would otherwise
  // silently wipe out whatever was previously saved.
  const dedupeKeys = useRef<Set<string>>(new Set());

  useEffect(() => {
    (async () => {
      try {
        const [rawNotif, rawSpecies] = await Promise.all([
          AsyncStorage.getItem(NOTIF_KEY),
          AsyncStorage.getItem(WATCHED_SPECIES_KEY),
        ]);
        if (rawNotif) {
          const parsed: AppNotification[] = JSON.parse(rawNotif);
          setNotifications(parsed);
          dedupeKeys.current = new Set(parsed.map((n) => n.dedupeKey));
        }
        if (rawSpecies) setWatchedSpecies(JSON.parse(rawSpecies));
      } catch {
        // fresh install / corrupt storage — just start empty
      } finally {
        setLoaded(true);
      }
    })();
  }, []);

  useEffect(() => {
    if (!loaded) return;
    AsyncStorage.setItem(NOTIF_KEY, JSON.stringify(notifications)).catch(() => {});
  }, [notifications, loaded]);

  useEffect(() => {
    if (!loaded) return;
    AsyncStorage.setItem(WATCHED_SPECIES_KEY, JSON.stringify(watchedSpecies)).catch(() => {});
  }, [watchedSpecies, loaded]);

  function addNotification(n: { dedupeKey: string; kind: AppNotification["kind"]; title: string; body: string }) {
    if (dedupeKeys.current.has(n.dedupeKey)) return;
    dedupeKeys.current.add(n.dedupeKey);
    setNotifications((prev) =>
      [
        { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, createdAt: new Date().toISOString(), read: false, ...n },
        ...prev,
      ].slice(0, MAX_NOTIFICATIONS)
    );
  }

  function markRead(id: string) {
    setNotifications((prev) => prev.map((n) => (n.id === id ? { ...n, read: true } : n)));
  }

  function markAllRead() {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  }

  function toggleWatchedSpecies(id: string) {
    setWatchedSpecies((prev) => (prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]));
  }

  const unreadCount = notifications.filter((n) => !n.read).length;

  return (
    <NotificationContext.Provider
      value={{
        notifications,
        unreadCount,
        loaded,
        markAllRead,
        markRead,
        addNotification,
        watchedSpecies,
        toggleWatchedSpecies,
        sheetOpen,
        openSheet: () => setSheetOpen(true),
        closeSheet: () => setSheetOpen(false),
      }}
    >
      {children}
    </NotificationContext.Provider>
  );
}

export function useNotifications(): NotificationContextValue {
  const ctx = useContext(NotificationContext);
  if (!ctx) throw new Error("useNotifications must be used within NotificationProvider");
  return ctx;
}
